### ISSUE TITLE
How to use webchat in rasa_core 0.11.1

### ISSUE THREAD

**Issue by cooelf** [mrbot-ai/rasa-addons#17]
Hi, thanks for your rasa-addons. I hope to use the webchat UI for rasa core but encounter some issues.
My rasa_core version is 0.11.1.
**1. 'HttpInputChannel' is not existed in rasa_core 0.11.1.**

```
Traceback (most recent call last):
  File "webchat.py", line 4, in <module>
    from rasa_addons.webchat import WebChatInput, SocketInputChannel
  File "/data/coulson/prj/WeatherBot/rasa_addons/webchat/__init__.py", line 4, in <module>
    from rasa_core.channels import InputChannel, OutputChannel, HttpInputChannel, UserMessage
ImportError: cannot import name 'HttpInputChannel'
```

After I delete the import 'HttpInputChannel' and use 'InputChannel' for the SocketInputChannel
class SocketInputChannel(InputChannel), this issues disappeared but a new issue come out.

**2. How to use "SocketInputChannel"?**

```
from rasa_addons.webchat import WebChatInput, SocketInputChannel
agent = Agent.load(...)
input_channel = WebChatInput(static_assets_path=os.path.join(os.path.dirname(os.path.realpath(__file__)), 'static'))
agent.handle_channel(SocketInputChannel(5500, "/bot", input_channel))
```
I follow the instruction above to use webchat channel but the channel has been modified in the new rasa core.  It seems I need to use in this way.

`agent.handle_channels([input_channel],2690,serve_forever=True)`

I don't know how to use the SocketInputChannel then... My code is as follows.

```
from rasa_addons.webchat import WebChatInput, SocketInputChannel
from rasa_core.agent import Agent
current_path = "/data/coulson/prj/WeatherBot/static"
agent = Agent.load("/data/coulson/prj/_rasa_chatbot/projects/dialogue", "/data/coulson/prj/_rasa_chatbot/projects/ivr_nlu/demo")
input_channel = WebChatInput(static_assets_path=os.path.join(current_path, 'static'))
agent.handle_channels(SocketInputChannel(5500, "/", input_channel)) 
```

or do I need to modify "SocketInputChannel" class to make it?

```
Traceback (most recent call last):
  File "webchat.py", line 14, in <module>
    SocketInputChannel(5500, "/", input_channel)
TypeError: object() takes no parameters
```

Hope for your reply. Thanks in advance!

**Comment by cooelf** [comment]
I have found the solution in Issue #16 but it still not works. Maybe I have missed something.
The log is 
```
message handler error
Traceback (most recent call last):
  File "/data/coulson/env/conda/envs/chatbot/lib/python3.6/site-packages/engineio/server.py", line 423, in _trigger_event
    return self.handlers[event](*args)
  File "/data/coulson/env/conda/envs/chatbot/lib/python3.6/site-packages/socketio/server.py", line 522, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/data/coulson/env/conda/envs/chatbot/lib/python3.6/site-packages/socketio/server.py", line 458, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/data/coulson/env/conda/envs/chatbot/lib/python3.6/site-packages/socketio/server.py", line 461, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/data/coulson/env/conda/envs/chatbot/lib/python3.6/site-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/data/coulson/prj/testBot/rasa_core/channels/socketio.py", line 142, in handle_message
    message = UserMessage(data['message'], output_channel, sid,
TypeError: string indices must be integers

```
My code is

```
#!/usr/bin/env python
import os
from rasa_core.channels.socketio import SocketIOInput
from rasa_core.agent import Agent
agent = Agent.load("/data/coulson/prj/_rasa_chatbot/projects/dialogue", "/data/coulson/prj/_rasa_chatbot/projects/ivr_nlu/demo")
agent.handle_channels([SocketIOInput()], 2690, serve_forever=True)
```
and in the static file
```
<div id="webchat"/>
<script src="webchat.js"></script>
<script>
    WebChat.default.init({
        selector: "#webchat",
        initPayload: "hello",
        socketUrl: "http://localhost:2690/",
        title: "Title"
        subtitle: "Subtitle"
        profileAvatar: "robotic.png",
        showCloseButton: true,
        fullScreenMode: false
    })
</script>
```
The webpage is served by `python -m http.server 8250`, within the static folder.

Hope for your reply. Thanks in advance!

**Comment by satishAarbor** [comment]
Are you resolved this issue?

**Comment by satishAarbor** [comment]
Are you resolved this issue?

**Comment by Noarah** [comment]
@cooelf  please could you please explain more what is in static file ? i tried what you did but nothing appeared as UI

**Comment by cooelf** [comment]
@satishAarbor @Noarah Thank you all! I have resolved the issue, it is because I was using the old webchat.js. After I change it to https://storage.googleapis.com/mrbot-cdn/webchat-latest.js, it works fine. Thanks!
